import { chmodSync, existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { DesktopProviderConfig, RuntimeConfigState } from '@cc/superai-contracts';
import type { AgentLaunchDefaults, AgentLaunchResolverInput, AgentModelResolverInput } from '../shared/definition.js';
import { ensurePrivateDir, getProviderDefaultModelId, projectLocalStateDir } from '../shared/launch-utils.js';

const HERMES_DEFAULT_MODEL = 'gpt-4o-mini';

export function resolveHermesModel(input: AgentModelResolverInput): string {
  if (input.rawModel.trim()) {
    return input.normalizedModel;
  }
  return firstProviderModelId(input.providers) || input.normalizedModel || HERMES_DEFAULT_MODEL;
}

export function buildHermesLaunchConfig(input: AgentLaunchResolverInput): AgentLaunchDefaults {
  const env: Record<string, string> = { HERMES_YOLO_MODE: '1' };
  const provider = input.providers[0];
  if (provider && (provider.base_url || provider.api_key || provider.model)) {
    const hermesHome = ensureHermesHome(input.configState, input.project, input.providers, input.model);
    env.HERMES_HOME = hermesHome;
  }
  return {
    command: 'hermes',
    args: ['acp'],
    env,
  };
}

function ensureHermesHome(
  configState: RuntimeConfigState,
  project: AgentLaunchResolverInput['project'],
  providers: DesktopProviderConfig[],
  model: string,
): string {
  const workspaceId = String(project.workspace_id || project.name || 'workspace');
  const homeDir = projectLocalStateDir(configState, 'hermes-homes', workspaceId);
  ensurePrivateDir(homeDir);
  const configPath = join(homeDir, 'config.yaml');
  const desired = renderHermesConfig(providers, model);
  if (!existsSync(configPath) || readFileSync(configPath, 'utf8') !== desired) {
    writeFileSync(configPath, desired, { encoding: 'utf8', mode: 0o600 });
    chmodSync(configPath, 0o600);
  }
  return homeDir;
}

function renderHermesConfig(providers: DesktopProviderConfig[], model: string): string {
  const provider = providers[0];
  const baseUrl = String(provider?.base_url || '').trim();
  const apiKey = String(provider?.api_key || '').trim();
  const modelName = (model || firstProviderModelId(providers) || HERMES_DEFAULT_MODEL).trim();
  const lines: string[] = [
    '# Generated by AgentDock Local AI Core from workspace provider config.',
    '# Edits here are overwritten on the next agent launch.',
    'model:',
    `  default: ${yamlString(modelName)}`,
    '  provider: custom',
  ];
  if (baseUrl) {
    lines.push(`  base_url: ${yamlString(baseUrl)}`);
  }
  if (apiKey) {
    lines.push(`  api_key: ${yamlString(apiKey)}`);
  }
  lines.push('toolsets:', '  - hermes-cli');
  lines.push('agent:', '  max_turns: 90');
  return `${lines.join('\n')}\n`;
}

function firstProviderModelId(providers: DesktopProviderConfig[]): string {
  for (const provider of providers) {
    const modelId = getProviderDefaultModelId(provider);
    if (modelId) {
      return modelId;
    }
  }
  return '';
}

function yamlString(value: string): string {
  const escaped = String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  return `"${escaped}"`;
}
